//package com.szmengran.chatgpt.domain.chat.dto;
//import com.fasterxml.jackson.annotation.JsonProperty;
//import lombok.Data;
//
///**
// * A chat completion generated by GPT-3.5
// */
//@Data
//public class ChatChoice {
//
//    /**
//     * This index of this completion in the returned list.
//     */
//    private Integer index;
//
//    /**
//     * The {@link ChatMessageRole#assistant} message which was generated.
//     */
//    private ChatMessage message;
//
//    /**
//     * The reason why GPT-3 stopped generating, for example "length".
//     */
//    @JsonProperty("finish_reason")
//    private String finishReason;
//}
