package com.szmengran.chatgpt.infrastructure.openai.dto.edit;

import lombok.Data;

/**
 * An edit generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
@Data
public class EditChoice {

    /**
     * The edited text.
     */
    private String text;

    /**
     * This index of this completion in the returned list.
     */
    private Integer index;
}
